In [1]:
import pandas as pd

In [2]:
datos_inventario = {
    "id_producto": [1, 2, 3, 4, 5],
    "producto": ["Notebook", "Mouse", "Teclado", "Monitor", "Auriculares"],
    "categoria": ["Tecnología", "Accesorios", "Accesorios", "Tecnología", "Audio"],
    "stock": [15, 40, 25, 18, 30],
    "precio": [850000, 15000, 28000, 220000, 45000]
}

In [3]:
inventario = pd.DataFrame(datos_inventario)

In [4]:
inventario

   id_producto     producto   categoria  stock  precio
0            1     Notebook  Tecnología     15  850000
1            2        Mouse  Accesorios     40   15000
2            3      Teclado  Accesorios     25   28000
3            4      Monitor  Tecnología     18  220000
4            5  Auriculares       Audio     30   45000

In [5]:
inventario.to_excel("inventario.xlsx", index=False)

In [2]:
import pandas as pd

In [3]:
ventas = pd.read_csv("ventas.csv")

In [4]:
ventas

   id_venta       fecha     producto  cantidad  precio  id_cliente
0         1  2026-08-01     Notebook         2  850000         101
1         2  2026-08-02        Mouse         5   15000         102
2         3  2026-08-03      Teclado         3   28000         103
3         4  2026-08-04      Monitor         2  220000         101
4         5  2026-08-05  Auriculares         4   45000         104
5         6  2026-08-06     Notebook         1  850000         105
6         7  2026-08-07        Mouse         8   15000         102
7         8  2026-08-08      Teclado         2   28000         106
8         9  2026-08-09      Monitor         3  220000         103
9        10  2026-08-10  Auriculares         6   45000         104

In [5]:
clientes = pd.read_json("clientes.json")

In [6]:
clientes

   id_cliente  nombre      ciudad  edad
0         101     Ana     Ushuaia    35
1         102  Carlos  Río Grande    42
2         103   Laura     Ushuaia    29
3         104  Martín     Tolhuin    38
4         105   Sofía     Ushuaia    31
5         106   Diego  Río Grande    45

In [7]:
inventario = pd.read_excel("inventario.xlsx")

In [8]:
inventario

   id_producto     producto   categoria  stock  precio
0            1     Notebook  Tecnología     15  850000
1            2        Mouse  Accesorios     40   15000
2            3      Teclado  Accesorios     25   28000
3            4      Monitor  Tecnología     18  220000
4            5  Auriculares       Audio     30   45000

In [9]:
ventas.head()

   id_venta       fecha     producto  cantidad  precio  id_cliente
0         1  2026-08-01     Notebook         2  850000         101
1         2  2026-08-02        Mouse         5   15000         102
2         3  2026-08-03      Teclado         3   28000         103
3         4  2026-08-04      Monitor         2  220000         101
4         5  2026-08-05  Auriculares         4   45000         104

In [10]:
clientes.head()

   id_cliente  nombre      ciudad  edad
0         101     Ana     Ushuaia    35
1         102  Carlos  Río Grande    42
2         103   Laura     Ushuaia    29
3         104  Martín     Tolhuin    38
4         105   Sofía     Ushuaia    31

In [11]:
inventario.head()

   id_producto     producto   categoria  stock  precio
0            1     Notebook  Tecnología     15  850000
1            2        Mouse  Accesorios     40   15000
2            3      Teclado  Accesorios     25   28000
3            4      Monitor  Tecnología     18  220000
4            5  Auriculares       Audio     30   45000

In [12]:
len(clientes)

6

In [13]:
inventario["stock"].mean()

np.float64(25.6)